#spring active env
spring:
    application:
        name: wjw
    profiles:
        active: integration
        
        
#server config
server:
    tomcat:
        max-threads: 700
        uri-encoding: UTF-8
    compression:
        enabled: true
        mime-types: application/json,application/javascript,application/xhtml+xml,text/html,text/xml,text/plain,text/css
    error.whitelabel:
        path: /error
        enabled: true # Enable the default error page displayed in browsers in case of a server error.
    port: 8080
    
    

spring.thymeleaf: 
    cache: false # Enable template caching.
    check-template-location: true
    content-type: text/html # Content-Type value.
    enabled: true # Enable MVC Thymeleaf view resolution.
    encoding: UTF-8 # Template encoding.
    mode: HTML5
    prefix: "classpath:/templates/" # Prefix that gets prepended to view names when building a URL.
    suffix: ".html" # Suffix that gets appended to view names when building a URL.
    
proxy: 
    key: NKKBZ-FLIKI-6ZBGN-5DJVM-5FWST-FNBF3
    districtUrl: http://apis.map.qq.com/ws/district/v1/getchildren?id={id}&key=${proxy.key}
    