# DATASOURCE
com.goodlaike.wjw.datasource: 
    url: jdbc:mysql://rm-wz93f2rzc9ne11bi8.mysql.rds.aliyuncs.com/wjw?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC 
    username: root_wjw
    password: Root_wjw
    driverClassName: com.mysql.cj.jdbc.Driver
    max-active: 50
    max-idle: 25
    min-idle: 25
    initial-size: 25
    max-wait: 10000
    testWhileIdle: true
    validationQuery: select 1
    validationQueryTimeout: 1
    validationInterval: 120000
    
server.port: 80